name: Electron App

on:
  push:
    branches: [master, ashinn/combined]
  pull_request:
    branches: [master, ashinn/combined]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    steps:
      - name: Force LF line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x

      - name: Install dbus on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update -q
          sudo apt-get install -y libdbus-1-dev


      - name: Install dependencies
        run: npm ci

      - name: Set build arch
        id: set_arch
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "arch=win" >> $GITHUB_OUTPUT
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "arch=mac" >> $GITHUB_OUTPUT
          else
            echo "arch=linux" >> $GITHUB_OUTPUT
          fi

      - name: Build Electron app
        run: npm run build:${{ steps.set_arch.outputs.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: electron/out/
